title: BlockChain Tech Srbija Blog
description: Blog o najnovijim tehnološkim dostignućima 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jovan Stojanović
user_description: Experienced professional with a wide range of skills and knowledge. Adapts quickly to new challenges and tasks. Finds effective and practical solutions for the general benefit.
user_title: Software Developer
email: jovan.geodux@gmail.com
twitter_username: jovan100janovic
github_username:  infinitEnigma
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
